

services:
  influxdb:
    image: influxdb:2.7
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
#    entrypoint: ["./entrypoint.sh"]
    environment:
      INFLUXD_PROMETHEUS_ON: "true"
      INFLUXD_PROMETHEUS_BIND_ADDRESS: ":8089"
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
      - "8089:8089"
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.5.0
    container_name: toxiproxy
    ports:
      - "8474:8474"   # Toxiproxy admin API
      - "8085:8085"   # Proxy port fot influxdb
      - "5433:5433"   # Proxy port for postgres
    depends_on:
      - influxdb
      - postgres
  toxiproxy-init:
    image: curlimages/curl:8.5.0
    container_name: toxiproxy-init
    depends_on:
      - toxiproxy
      - influxdb
      - postgres
    volumes:
      - ./toxiproxy-init.sh:/toxiproxy-init.sh:ro
    entrypoint: [ "/bin/sh", "/toxiproxy-init.sh" ]
    restart: "no"
  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "C:/master anu 1/ceretare/project/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  postgres:
    image: postgres:16
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/dat

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://authuser:authpass@postgres:5432/authdb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
volumes:
  grafana-storage:
  influxdb-storage:
  postgres-storage:
